### ISSUE TITLE
Feature request: virtual text colorcolumn

### ISSUE THREAD

**Issue by mawkler** [Bekaboo/deadcolumn.nvim#2]
This plugin looks awesome! It would be great if it had support for virtual text custom character for the column like [virtcolumn.nvim](https://github.com/xiyaowong/virtcolumn.nvim) and [virt-column.nvim](https://github.com/lukas-reineke/virt-column.nvim) do.

**Comment by Bekaboo** [comment]
Thanks for suggestion! Will look into it when I have time.

**Comment by Bekaboo** [comment]
Sorry, I have to close this because I realized that using virtual text needs a complete rewrite -- deadcolumn depends on the builtin colorcolumn to draw the line and only changes `winhl` to reveal/conceal it while using virtualtext to replicate a colorcolumn is a completely different approach and has too many edge cases to deal with due to how nvim/vim handles global-local variables.
